dist: xenial
language: python
python:
  - "3.6"

git:
  submodules: false

# command to install dependencies
install:
  - pip install --progress-bar off --quiet -r requirements.txt

# command to run tests
script:
  - pytest
